AWS_CONFIG= {
    'AWS_SERVER_PUBLIC_KEY':'AKIAJXW2BUBHALSKDFPQ',
    'AWS_SERVER_SECRET_KEY':'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'
}

CURRENT_REGION = 'eu-central-1'

RDS_CONFIG={
    'MASTER_USERNAME':'master',
    'MASTER_PASSWORD':'justanotherpassword'
}