AWS_CONFIG= {
    'AWS_SERVER_PUBLIC_KEY':'AKIAJHK4UKVNUFHNWRVQ',
    'AWS_SERVER_SECRET_KEY':'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'
}

CURRENT_REGION = 'eu-central-1'

RDS_CONFIG={
    'MASTER_USERNAME':'master',
    'MASTER_PASSWORD':'justanotherpassword'
}